<a href="https://colab.research.google.com/github/fowardelcac/TensorFLow_Fcc/blob/main/1_tf_fundmentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/fowardelcac/TensorFLow_Fcc.git

Cloning into 'TensorFLow_Fcc'...
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 10 (delta 0), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (10/10), 4.18 KiB | 4.18 MiB/s, done.


What is a tensor?

https://www.youtube.com/watch?v=f5liqUk0ZTw

## intro to tensors

In [2]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [ ]:
#create tensors with tf.constants
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#  numb of dim
scalar.ndim

0

In [ ]:
# create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix = tf.constant([[10, 10],
                      [5, 5]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [ 5,  5]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
matriz = tf.constant([[10., 10.1],
                      [10., 10.1],
                      [5.1, 5.2]], dtype=tf.float32)

In [ ]:
matriz

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10. , 10.1],
       [10. , 10.1],
       [ 5.1,  5.2]], dtype=float32)>

In [ ]:
# ndim es la cantidad de elementos por vector
matriz.ndim

2

In [ ]:
tf.constant([[10., 10.1, 11.],
                      [10., 88, 10.1],
                      [5.1, 9, 5.2]], dtype=tf.float32)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[10. , 10.1, 11. ],
       [10. , 88. , 10.1],
       [ 5.1,  9. ,  5.2]], dtype=float32)>

So:
- Scalar: single numb
- Vector: numb with direccion
- Matrix: > 2 dim array of numbers
- Tensor: n-dim array of numbers:
    *   0-dim is a scalar
    * 1-dim is a vector



## creating tensor swith tf.variable

In [ ]:
changeable_ts = tf.Variable([10, 6])
unchangeable = tf.constant([10,8])

In [ ]:
changeable_ts

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  6], dtype=int32)>

In [ ]:
unchangeable

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  8], dtype=int32)>

In [ ]:
changeable_ts[0] = 7

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
changeable_ts[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 6], dtype=int32)>

In [ ]:
unchangeable[0].assign(7)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

x lo general no los vas a usar nunca a .constant/.variable tf lo hace por detras


# Crating random ts

In [ ]:
random1 = tf.random.Generator.from_seed(42)
random1 = random1.normal(shape=(3, 2))

In [ ]:
random1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random2 = tf.random.Generator.from_seed(42)
random2 = random2.normal(shape=(3, 2))
random2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

## shuffle the order of elements in a tensor
- shuffle the data para que el orden no afecte al algo

In [ ]:
not_shafle =  tf.constant([
    [10, 7],
    [11, 4],
    [22, 4]
    ])
not_shafle

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [11,  4],
       [22,  4]], dtype=int32)>

In [ ]:
not_shafle.ndim


2

In [ ]:
tf.random.shuffle(value = not_shafle)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[22,  4],
       [11,  4],
       [10,  7]], dtype=int32)>

# Otras formas de tensors

In [ ]:
tf.ones([10, 6])

<tf.Tensor: shape=(10, 6), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros(shape=(2, 3)) #tambien se oede pasar el shape asi

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

### np.array -> tensors
La diferencia esta en que tensor pueden ser procesados en una gpu mas rapido

In [ ]:
import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A)
B = tf.constant(numpy_A, shape=(2, 3, 4))

In [ ]:
A, B

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>)

## Indexing tensors
Works as python list

In [11]:
rank = tf.Variable([[[
    [10, 2, 3, 4],
    [10, 4, 5, 6],
    [4, 5, 6, 7],
    [5, 6, 7, 5]
    ]]])
rank

<tf.Variable 'Variable:0' shape=(1, 1, 4, 4) dtype=int32, numpy=
array([[[[10,  2,  3,  4],
         [10,  4,  5,  6],
         [ 4,  5,  6,  7],
         [ 5,  6,  7,  5]]]], dtype=int32)>

In [12]:
rank[:2, :2, :2, :2]

<tf.Tensor: shape=(1, 1, 2, 2), dtype=int32, numpy=
array([[[[10,  2],
         [10,  4]]]], dtype=int32)>

In [13]:
rank.shape

TensorShape([1, 1, 4, 4])

In [14]:
rank[:1, :1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 1), dtype=int32, numpy=array([[[[10]]]], dtype=int32)>

In [18]:
rank2 = tf.constant([[10, 5], [3, 4]])
rank2.shape, rank2.ndim

(TensorShape([2, 2]), 2)

In [22]:
# obtener el ultimo elem
rank2[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 4], dtype=int32)>

In [23]:
#add extra dim
rank3 = rank2[..., tf.newaxis]
rank3

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 5]],

       [[ 3],
        [ 4]]], dtype=int32)>

# Maniuplating tensors

In [25]:
# el tennsor original no cambia
tensor = tf.constant([[10, 5], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 15],
       [13, 14]], dtype=int32)>

In [26]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  50],
       [ 30,  40]], dtype=int32)>

In [27]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -5],
       [-7, -6]], dtype=int32)>

In [28]:
# use tf funciton
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  50],
       [ 30,  40]], dtype=int32)>

# Matrix op

In [30]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[115,  70],
       [ 42,  31]], dtype=int32)>

In [31]:
t1 = tf.constant([
    [1, 2, 5],
    [7, 2, 1],
    [3, 3, 3]
])
t2 = tf.constant([
    [3, 5],
    [6, 7],
    [1, 8]
])

In [32]:
tf.matmul(t1, t2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [33]:
t1 @ t2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

#Changin data typ

In [34]:
b = tf.constant([1.4])
b.dtype

tf.float32

In [35]:
b = tf.cast(b, dtype=tf.float16)
b.dtype

tf.float16

In [37]:
b

<tf.Tensor: shape=(1,), dtype=float16, numpy=array([1.4], dtype=float16)>

# agregation ts
agg ts = condensign them from multiple values down to a smaller amount of values

In [38]:
#get the abs value
d = tf.constant([-1, -1])
d

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-1, -1], dtype=int32)>

In [39]:
tf.abs(d)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 1], dtype=int32)>

In [41]:
# var
tf.math.reduce_variance(tf.cast(d, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

# one hot encoding

In [46]:
lista = [0, 1, 2]
tf.one_hot(lista, depth=3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [49]:
# custom values
tf.one_hot(lista, depth=3, on_value='jj', off_value='22')

<tf.Tensor: shape=(3, 3), dtype=string, numpy=
array([[b'jj', b'22', b'22'],
       [b'22', b'jj', b'22'],
       [b'22', b'22', b'jj']], dtype=object)>