<a href="https://colab.research.google.com/github/fowardelcac/TensorFLow_Fcc/blob/main/1_Intro_to_TF/Just_basic_stuff.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/fowardelcac/TensorFLow_Fcc.git

Cloning into 'TensorFLow_Fcc'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Total 4 (delta 0), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (4/4), done.


In [3]:
import tensorflow as tf


Tensors are a generalization of vecor and matrices to potentially higher dimensios, tf represents tensors as n.dimensonal arrays of base datatypes.   Each tensor has a data type and a shape

In [4]:
string = tf.Variable('String man', tf.string)
number = tf.Variable(2333, tf.int16)
floating = tf.Variable(2333, tf.float64)


In [7]:
string, number, floating

(<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'String man'>,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=2333>,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=2333>)

Rank/degree of tensors: number of dimensions invlved in the tensor, tensors created before have a rank of 0, 'cause they are scalars

In [8]:
rank1_t = tf.Variable(['Cryn'], tf.string)
rank2_t = tf.Variable([['1', '2'], ['j', ' k']], tf.string)

In [9]:
rank2_t

<tf.Variable 'Variable:0' shape=(2, 2) dtype=string, numpy=
array([[b'1', b'2'],
       [b'j', b' k']], dtype=object)>

In [11]:
print('El rank esta en numpy = ...')
tf.rank(rank2_t) # its like use .shape

El rank esta en numpy = ...


<tf.Tensor: shape=(), dtype=int32, numpy=2>

Shape: amount of elements per dimension

In [14]:
print(rank1_t.shape)
print(rank2_t.shape)
print('Dos listas con 3 dmensiones:', tf.Variable([['1', '2','dps'], ['j', ' k', 'kk']], tf.string).shape)
print('Rank:', tf.rank(tf.Variable([['1', '2','dps'], ['j', ' k', 'kk']], tf.string)))

(1,)
(2, 2)
Dos listas con 3 dmensiones: (2, 3)
Rank: tf.Tensor(2, shape=(), dtype=int32)


In [17]:
tf.ones([1, 2, 3])

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [18]:
t = tf.zeros([5, 5, 5, 5])
t

<tf.Tensor: shape=(5, 5, 5, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

  

In [19]:
t = tf.reshape(t, [625])
t

<tf.Tensor: shape=(625,), dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0